package:
  name: flask-cors
  version: "1.10.3"

source:
  fn: Flask-Cors-1.10.3.tar.gz
  url: https://pypi.python.org/packages/8d/ee/a72a909f125400d54b616e4c6de9df9512ea724340dfb09acf7ee0bbe39e/Flask-Cors-1.10.3.tar.gz
  md5: 4f3c75ace0f724d1de167bd73745c965
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-cors = flask-cors:main
    #
    # Would create an entry point called flask-cors that calls flask-cors.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask >=0.9
    - six

  run:
    - python
    - flask >=0.9
    - six

test:
  # Python imports
  imports:
    - flask_cors

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/corydolphin/flask-cors
  license: MIT License
  summary: 'A Flask extension adding a decorator for CORS support'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
